decent/decent/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

alphanum_plus = "[a-zA-Z0-9-_]+"

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'decent.views.home', name='home'),
    # url(r'^decent/', include('decent.foo.urls')),
    
    ### User-facing (mostly) URLs: ###
    
    url(r'^$', 'bmarks.views.crud.bmark_list', name='home'),  # shows my + subscriptions if logged in, all on this install if logged out
    url(r'^about/$', 'django.views.generic.simple.direct_to_template', {'template': 'about.html',}, name='about'),
    url(r'^human/(?P<username>'+alphanum_plus+')/$', 'bmarks.views.crud.bmark_list', name='bmark_list_by_user'),
    url(r'^tag/(?P<tag>'+alphanum_plus+')/$', 'bmarks.views.crud.bmark_list', name='bmark_list_by_tag'),
    url(r'^subscriptions/$', 'bmarks.views.crud.add_subscription', name='subscription_page'),
    url(r'^subscribe/$', 'bmarks.views.crud.add_subscription', name='add_subscription'),
    url(r'^new/$', 'bmarks.views.crud.new_bookmark', name='new_bookmark'),  # typically not called via own template
    # url(r'^edit/(?P<bmark_id>\d+)/$', 'bmarks.views.crud.edit_bookmark', name='edit_bookmark'), ** hold off until other things work
    url(r'^delete/$', 'bmarks.views.crud.delete_bookmark', name='delete_bookmark'),  # not a separate template
    
    url(r'^login/$', 'bmarks.views.crud.login_view', name='login'),
    url(r'^logout/$', 'bmarks.views.crud.logout_view', name='logout'),
    
    # dangerous pattern
    url(r'^(?P<mode>\w+)/$', 'bmarks.views.crud.bmark_list', name='bmark_list_modal'),
    
    # Login/sign up

    # **Copy someone else's bookmark to mine, with my own tags etc.
    
    ### Federation API URLs: ###
    
    url(r'^human/(?P<username>'+alphanum_plus+')/update/$', 'bmarks.views.federators.receive_updates', name='receive_updates'),  # pings from subscribed-to users go here
    url(r'^human/(?P<username>'+alphanum_plus+')/subscribe/$', 'bmarks.views.federators.update_subscriber_info', name='update_subscriber_info'),  # pings when someone new subscribes or unsubscribes go here
    url(r'^human/(?P<username>'+alphanum_plus+')/get/last/(?P<num_updates>\d+)$', 'bmarks.views.federators.fetch_last_n_bmarks', name='fetch_last_n_bmarks'),  # request arbitrary number of bookmarks, reverse-chron order, get some json
    #url(r'^human/(?P<username>'+alpha-num_plus+')/get/since/<datetime>$', 'bmarks.views.fetch_bmarks_by_date', name='fetch_bmarks_by_date'),  # request all bookmarks after a certain datetime, get some json

)

decent/bmarks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_init, post_save
from django.dispatch import receiver

optional = dict(blank=True, null=True)

class Address(models.Model):
    username = models.CharField(max_length=20)
    domain = models.CharField(max_length=50, default="localhost")
    
    def __unicode__(self):
        return self.username + '@' + self.domain
        
    
class Human(User):
    # username
    # password
    # email
    address = models.OneToOneField(Address)
    
    
class Subscription(models.Model):
    id = models.IntegerField(unique=True, primary_key=True)
    username = models.CharField(max_length=20)
    domain = models.CharField(max_length=50, default="localhost")
    the_person_listening = models.ForeignKey(Human)
    last_received_update = models.DateTimeField(auto_now_add=True)
    
    def __unicode__(self):
        return 'From: ' + self.the_person_listening.username + ' to: ' + self.username + '@' + self.domain
        

class Subscriber(models.Model):
    username = models.CharField(max_length=20)
    domain = models.CharField(max_length=50, default="localhost")
    the_person_sending = models.ForeignKey(Human)
    last_updated = models.DateTimeField(auto_now_add=True)
    
    def __unicode__(self):
        return 'From: ' + self.the_person_sending.username + ' to: ' + self.username + '@' + self.domain
        
    
class Tag(models.Model):
    name = models.CharField(max_length=30, unique=True)
    
    def __unicode__(self):
        return self.name
    
    
class Bookmark(models.Model):
    owner = models.ForeignKey(Address, **optional)
    remote_owner = models.ForeignKey(Subscription, **optional)
    url = models.URLField()
    description = models.TextField(**optional)
    tags = models.ManyToManyField(Tag, **optional)
    time = models.DateTimeField(auto_now_add=True)  # auto on create
    # via (a given address)
    # is_private
    
    def __unicode__(self):
        return self.url
        
    class Meta:
        ordering = ['-time', 'owner']
   
   
### Signals handlers ###

@receiver(post_save, sender=Bookmark)
def bookmark_save(sender, **kwargs):
    if created:
        print "Received a hook for a new Bookmark!"
        print instance.url
    else:
        print "Received a hook for an old Bookmark."

decent/bmarks/forms.py
from django import forms

class BookmarkForm(forms.Form):
    url = forms.URLField(label="URL")
    tags = forms.CharField(required=False, label="tags")
    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 3}), required=False, label="description")
    
class SubscriptionForm(forms.Form):
    full_address = forms.CharField(label="username@domain.tld")

decent/bmarks/views/crud.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as login_function
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from bmarks.models import Bookmark, Tag, Human, Address, Subscriber, Subscription
from bmarks.forms import BookmarkForm, SubscriptionForm
import datetime
from itertools import chain
from operator import attrgetter
    
def bmark_list(request, username=None, tag=None, mode=None):
    if request.method == 'POST':
        if request.POST['form-type']:
            return login_view(request)
        else:
            form = BookmarkForm(request.POST)
            if form.is_valid():
                url = form.cleaned_data['url']
                tags = form.cleaned_data['tags']
                description = form.cleaned_data['description']
                human = request.user.human
                b = Bookmark(url=url, owner=human.address)
                if description:
                    b.description = description
                if tags:
                    b.save()
                    tag_list = tags.split(',')
                    print tags
                    for tag in tag_list:
                        tag = tag.strip()
                        if Tag.objects.filter(name=tag):
                            t = Tag.objects.get(name=tag)
                        else:
                            t = Tag(name=tag)
                            t.save()
                        b.tags.add(t)
                b.save()
            else:
                print form
            return redirect('home')
    elif request.method == 'GET':
        # default behavior: show all bookmarks
        bookmarks = Bookmark.objects.all()
        form = BookmarkForm()
        human = None
        subscriptions = None
        new_user_form = UserCreationForm()
        login_form = AuthenticationForm()
        
        if request.user.is_authenticated():
            human = Human.objects.get(username=request.user.username)
            if not mode:
                mode = "subs"
        else:
            if mode=="mine" or mode=="subs":
                redirect('home')
            else:
                mode="all"
        
        # get all for a given username
        if username:
            user = get_object_or_404(Human, username=username)
            bookmarks = bookmarks.filter(owner=user.address)
            if username == request.user.username:
                mine = True
        
        # get all with a certain tag
        elif tag:
            bookmarks = bookmarks.filter(tags=tag) 
        
        # show my bookmarks plus those of my subscriptions
        elif mode == 'subs':
            subscriptions = Subscription.objects.filter(the_person_listening=human)
            print subscriptions
            my_bookmarks = bookmarks.filter(owner=human.address)
            c = chain(my_bookmarks, [])
            for subscription in subscriptions:
                if subscription.domain == 'localhost':
                    h = Human.objects.get(username=subscription.username)
                    c = chain(c, bookmarks.filter(owner=h.address))
                else:
                    c = chain(c, bookmarks.filter(remote_owner=subscription))
            
            bookmarks = sorted(c, key=attrgetter('time'))
                    
        # show just my bookmarks
        elif mode == 'mine':
            bookmarks = bookmarks.filter(owner=human.address)
        
        context = {
            'bookmarks': bookmarks,
            'tags': Tag.objects.all(),
            'subscriptions': subscriptions,
            'human': human,
            'form': form,
            'mode': mode,
            'new_user_form': new_user_form,
            'login_form': login_form,
        }
        return render(request, 'listing.html', context)
        
        
def login_view(request):
    if request.method == 'POST':
        if request.POST['form-type'] == 'signup':
            print "signup form"
            print request.POST
            username = request.POST['username']
            password = request.POST['password1']
            if not Human.objects.filter(username=username):
                a = Address(username=username, domain='localhost')
                a.save()
                h = Human(username=username, password=make_password(password), address=a)
                h.save()
                print h
                user = authenticate(username=username, password=password)
                print "auth worked"
                login_function(request, user)
                print "logged in!"
                return redirect('home')
            else:
                try:
                    user = authenticate(username=username, password=password)
                    if user is not None:
                        login_function(request, user)
                        print "logged in!"
                        return redirect('home')
                except:
                    pass
            return redirect('home')
        else:
            form = AuthenticationForm(request.POST)
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login_function(request, user)
                return redirect('home')
    return redirect('home')
        
        
def logout_view(request):
    logout(request)
    return redirect('home')


@login_required 
def add_subscription(request):
    if request.method == "POST":
        human = request.user.human
        if request.POST['form-type']:
            form = SubscriptionForm(request.POST)
            if form.is_valid():
                address = form.cleaned_data['full_address'].split('@')
                if len(address) <= 2:
                    username = address[0]
                    domain = address[1]
        elif request.is_ajax():
            username = request.POST['username']
            domain = request.POST['domain']
            
        if domain == "localhost":
            h = get_object_or_404(Human, username=username)
            subscriber = Subscriber(username=human.username, domain="localhost", the_person_sending=h, last_updated=datetime.datetime.now())
            subscriber.save()
        else:
            # ping them to make a subscriber
            pass
        subscription = Subscription(username=username, domain=domain, the_person_listening=human, last_received_update=datetime.datetime.now())
        subscription.save()
        return redirect('subscription_page')

    else:
        if request.user.is_authenticated():
            human = request.user.human
            subscriptions = Subscription.objects.filter(the_person_listening=human)
            form = SubscriptionForm()
            context = {
                'subscriptions': subscriptions,
                'human': human,
                'form': form,
            }
            return render(request, 'subscriptions.html', context)
        else:
            redirect('login')
        

@login_required
def new_bookmark(request):
    pass

def delete_bookmark(request):
    message = ''
    mime='text'
    if request.is_ajax() and request.method == 'POST':
        if request.POST['bookmark_id']:
            bookmark_id = request.POST['bookmark_id'][9:]
            b = Bookmark.objects.get(pk=int(bookmark_id))
            b.delete()
            message = "Successfully deleted bookmark #" + bookmark_id
    return HttpResponse(message,mime)
    
def delete_subscription(request):
    message = ''
    mime='text'
    human = request.user.human
    if request.is_ajax() and request.method == 'POST':
        if request.POST['subscription_id']:
            subscription_id = request.POST['subscription_id'][13:]
            subscription = Subscription.objects.get(pk=int(subscription_id))
            if subscription.domain == "localhost":
                h = Human.objects.get(username=subscription.username)
                subscriber = Subscriber.objects.filter(username=human.username).filter(the_person_sending=h)[0]
                subscriber.delete()
            else:
                #ping other service
                pass
            subscription.delete()
            message = "Successfully deleted subscription #" + subscription_id
    return HttpResponse(message,mime)

decent/bmarks/views/federators.py
def receive_updates(request, username):
    pass
    
def update_subscriber_info(request, username):
    pass
    
def fetch_last_n_bmarks(request, username, num_updates=10):
    pass

decent/bmarks/templates/about.html
{% extends 'one_column_base.html' %}

{% block one-col %}

    <h3>about</h3>
    
    <p class="pullquote">"This is my [web bookmarks keeper]. <strong>There are many like it</strong>, but this one is mine."</p>
    
    <p>tamli is yet another social bookmarking application for storing interesting URLs from around the web. </p>
    
    <p>tamli is open source, so anyone can <a href="https://github.com/aldeka/gentlerobots">download the code</a>, modify it, and put it on their own server. </p>
    
    <p>tamli is also federated, which means that any tamli installation can talk to and share bookmarks with any other.</p>
    
    <p>If you don't have a computer of your own that you can use as a server, you can create an account on this tamli installation, just like any other software-as-a-service web application. If you do have a server, though, you can install your own tamli instance and have 100% control of your bookmarks data, while still being able to share bookmarks with your friends, acquaintances, role models, and frenemies via their own tamli instances. Neat, eh?</p>
    
    <p>The name of this application, tamli, is an acronym taken from part of <a href="http://en.wikipedia.org/wiki/Rifleman's_Creed">the US Marine Corp Rifleman's Creed</a>.</p>
    
    <p>There are many social bookmarking applications on the web, but this one is mine. And yours too, if you like!</p>
    
{% endblock one-col %}

decent/bmarks/templates/base.html
<!doctype html>
<html lang="en" dir="ltr">
    <head>
        <title>tamli
            {% block title %} - Home{% endblock %}
        </title>
        
        {% block less %}
        <link rel="stylesheet/less" href="/static/less/base.less"/>
        {% endblock less %}
        
        <script type='text/javascript' src='https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js'></script>
        <script src="/static/js/less-1.3.0.min.js" type="text/javascript"></script>
        
        {% block js %}
        
        <script type="text/javascript" src="static/js/scripts.js"></script>
        <script type="text/javascript">
            $(document).ready(function(){
                $('.delete').click(function(e){
                    e.preventDefault();
                    var bookmark = $(this).parent();
                    var id = $(bookmark).attr('id');
                    console.log('deleting ' + id);
                    $.post(
                        "{% url delete_bookmark %}",
                        {
                            'bookmark_id': id,
                        },
                        function(data){
                            $(bookmark).hide();
                        }
                    );

                });
            });
        </script>
        {% endblock js %}
        
        <!--[if lt IE 8]>
        <script src="http://ie7-js.googlecode.com/svn/version/2.0(beta3)/IE8.js"
        type="text/javascript"></script>
        <![endif]-->
    </head>
    
    <body class="{% block bodyclass%}{% endblock bodyclass %}">
    <div id="container">
        <div id="header">
            <div id="nav">
                <a href="{% url home %}">home</a> | {% comment %}<a href="{% url about %}">about</a> | {% endcomment %}
                {% if user.is_authenticated %}
                <a href="{% url subscription_page %}">my subscriptions</a> | <a href="{% url logout %}">logout</a>
                {% else %}
                <a href="{% url login %}" id="signup" data-action="show-modal">signup</a> | 
                <a href="{% url login %}" id="login" data-action="show-modal">login</a>
                {% endif %}
            </div>
            <div id="login-form" class="modal admin-form hidden">
                <form method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="form-type" value="login"/>
                    {{ login_form.as_p }}
                    <br/>
                    <p><input type="submit" value="login" class="button"/></p>
                </form>
            </div>
            <div id="signup-form" class="modal admin-form hidden">
                <form method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="form-type" value="signup"/>
                    {{ new_user_form.as_p }}
                    <br/>
                    <p><input type="submit" value="sign up" class="button"/></p>
                </form>
            </div>
            <h1><a href="{% url home %}" title="there are many like it, but this one is mine">tamli</a></h1>
            <h2>yet another social bookmarking app</h2>
        </div>
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <div id="footer">
        <!--- Created for Django Dash 2012 -->
    </div>
    </body>
</html>

decent/bmarks/templates/listing.html
{% extends 'two_column.html' %}

{% block main %}
    <ul id="bookmark-nav">
        <li><a href="{% url bmark_list_modal 'all' %}" {% if mode == "all" %}class="active"{% endif %} >all bookmarks</a></li>
        {% if user.is_authenticated %}
        <li><a href="{% url bmark_list_modal 'subs' %}" {% if mode == "subs" %}class="active"{% endif %}>my bookmarks and subscriptions</a></li>
        <li><a href="{% url bmark_list_modal 'mine' %}" {% if mode == "mine" %}class="active"{% endif %}>just my bookmarks</a></li>
        {% endif %}
    </ul>
    {% if bookmarks %}
    <ul class="bookmark-list">
    {% for bookmark in bookmarks %}
        <li id="bookmark-{{ bookmark.id }}" class="bookmark">
            {% if bookmark.owner.human and user.is_authenticated and user.username == bookmark.owner.human.username %}
                <span id="delete-{{ bookmark.id }}" class="delete clickable">x</span>
            {% endif %}
            <a href="{{ bookmark.url }}">{{ bookmark.url }}</a>
            <span class="metadata">
            {% if not mine %}
             -- posted by 
                {% if bookmark.owner.human %}
                    <a href="{% url bmark_list_by_user bookmark.owner.human.username %}">{{ bookmark.owner.human.username }}</a>
                {% else %}
                    {{ bookmark.owner.username }}
                {% endif %}
                {% if user.is_authenticated and bookmark.owner != user.human.address and bookmark.owner not in subscriptions %}
                <a class="subscribe-link" href="{% url add_subscription %}">subscribe</a>
                {% endif %}
            {% endif %} -- added {{ bookmark.time.date|date:"m.d.y" }}</span>
            
            {% if bookmark.description %}
                <p class="description">{{ bookmark.description }}</p>
            {% endif %}
            
            {% if bookmark.tags %}
                <ul class="tags">
                {% for tag in bookmark.tags.all %}
                    <li class="tag"><a href="{% url bmark_list_by_tag tag.name %}">{{ tag.name }}</a></li>
                {% endfor %}
                </ul>
            {% endif %}
        </li>
    {% endfor %}
    </ul>
    {% else %}
    <h3>No bookmarks found, sorry :(</h3>
    {% endif %}
{% endblock main %}

decent/bmarks/templates/one_column_base.html
{% extends 'base.html' %}

{% block content %}

    <div id="one-column-main">
        {% block one-col %}
        {% endblock one-col %}
    </div>
    
{% endblock content %}

decent/bmarks/templates/subscriptions.html
{% extends 'one_column_base.html' %}

{% block one-col %}
<h3>add new subscription:</h3>
{% if form %}
    <form id="new-subscription" method="POST">
        {% csrf_token %}
        <input type="hidden" name="form-type" value="new-subscription">
        {{ form.as_p }}
        <p><input type="submit" value="submit" class="button"/></p>
    </form>
{% endif %}

<h3>subscriptions:</h3>

     <ul class="subscription-list">
    {% for subscription in subscriptions %}
        <li id="subscription-{{ subscription.id }}" class="subscription">
        {% if subscription.domain == 'localhost' %}
            <a href="{% url bmark_list_by_user subscription.username %}">{{ subscription.username }}@{{ subscription.domain }}</a>
        {% else %}
            {{ subscription.username }}@{{ subscription.domain }}
        {% endif %} 
        <span id="delete-{{ subscription.id }}" class="delete clickable">x</span>
        </li>
    {% endfor %}
    </ul>
    
{% endblock one-col %}

decent/bmarks/templates/two_column.html
{% extends 'base.html' %}

{% block content %}

    <div id="sidebar">
        {% block sidebar %}
            {% if user.is_authenticated and form %}
            <div id="add-new-bookmark-widget" class="widget">
                <h3>add a bookmark:</h3>
                    <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="submit :-)" id="big-submit-button" class="button"/>
                    </form>
            </div>
            {% endif %}
            <div class="widget" id="tag-widget">
                <h3>tags:</h3>
                <ul>
                {% for tag in tags %}
                    {% if tag.bookmark_set.count %}
                    <li><a href="{% url bmark_list_by_tag tag.name %}">{{ tag.name }} ({{ tag.bookmark_set.count }})</a></li>
                    {% endif %}
                {% endfor %}
                </ul>
            </div>
        {% endblock sidebar %}
    </div>
    <div id="main">
        {% block main %}
        {% endblock main %}
    </div>
    
{% endblock content %}